# Window dimensions
WINDOW_WIDTH = 500
WINDOW_HEIGHT = 600

# Cell dimensions
CELL_SIZE = 50

# Board colors
CELL_COLOR = (255, 255, 255)
CELL_TEXT_COLOR = (0, 0, 0)
SELECTED_CELL_COLOR = (200, 200, 200)
BLOCK_COLOR = (0, 0, 0)

# Button dimensions
BUTTON_HEIGHT = 50
BUTTON_WIDTH = 100
BUTTON_SIZE = (BUTTON_WIDTH, BUTTON_HEIGHT)

# Button positions
SOLVE_BUTTON_POS = (50, 520)
NEW_BOARD_BUTTON_POS = (200, 520)
RESET_BUTTON_POS = (350, 520)

# Button colors
BUTTON_COLOR = (255, 255, 255)
BUTTON_HOVER_COLOR = (150, 150, 150)
BUTTON_BORDER_COLOR = (0, 0, 0)

# Button sizes
SOLVE_BUTTON_SIZE = (BUTTON_WIDTH, BUTTON_HEIGHT)
NEW_BOARD_BUTTON_SIZE = (BUTTON_WIDTH, BUTTON_HEIGHT)
RESET_BUTTON_SIZE = (BUTTON_WIDTH, BUTTON_HEIGHT)

# Text sizes
TITLE_SIZE = 50
BUTTON_TEXT_SIZE = 30

# Text colors
TITLE_COLOR = (0, 0, 0)

# Text positions
TITLE_POS = (50, 50)

# Text fonts
FONT_NAME = None

# Clue count for each board size
EASY_CLUES = 5
INTERMEDIATE_CLUES = 12
STANDARD_CLUES = 17

# Background color
BACKGROUND_COLOR = (255, 255, 255)
